/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_classpath_VMStackWalker */

#ifndef _Included_gnu_classpath_VMStackWalker
#define _Included_gnu_classpath_VMStackWalker
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     gnu_classpath_VMStackWalker
 * Method:    getContextSize
 * Signature: ()I
 */
  JNIEXPORT static jint JNICALL
    Java_gnu_classpath_VMStackWalker_getContextSize (JNIEnv *, jclass);

/*
 * Class:     gnu_classpath_VMStackWalker
 * Method:    fillContext
 * Signature: ([Ljava/lang/Class;)V
 */
  JNIEXPORT static void JNICALL Java_gnu_classpath_VMStackWalker_fillContext
    (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_classpath_VMStackWalker
 * Method:    getCallingClass
 * Signature: ()Ljava/lang/Class;
 */
  JNIEXPORT static jclass JNICALL
    Java_gnu_classpath_VMStackWalker_getCallingClass (JNIEnv *, jclass);

/*
 * Class:     gnu_classpath_VMStackWalker
 * Method:    getCallingClassLoader
 * Signature: ()Ljava/lang/ClassLoader;
 */
  JNIEXPORT static jobject JNICALL
    Java_gnu_classpath_VMStackWalker_getCallingClassLoader (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
