/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Throwable */

#ifndef _Included_java_lang_Throwable
#define _Included_java_lang_Throwable
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     java_lang_Throwable
 * Method:    nativeGetStackTraceList
 * Signature: ()Ljava/lang/StackTraceElement;
 */
  JNIEXPORT static jobject JNICALL
    Java_java_lang_Throwable_nativeGetStackTraceList (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
