/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_VMObjectStreamClass */

#ifndef _Included_java_io_VMObjectStreamClass
#define _Included_java_io_VMObjectStreamClass
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    hasClassInitializer
 * Signature: (Ljava/lang/Class;)Z
 */
  JNIEXPORT static jboolean JNICALL
    Java_java_io_VMObjectStreamClass_hasClassInitializer (JNIEnv *, jclass,
							  jclass);

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setDoubleNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;D)V
  JNIEXPORT static void JNICALL
    Java_java_io_VMObjectStreamClass_setDoubleNative (JNIEnv *, jclass,
						      jobject, jobject,
						      jdouble);
 */

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setFloatNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;F)V
  JNIEXPORT static void JNICALL
    Java_java_io_VMObjectStreamClass_setFloatNative (JNIEnv *, jclass,
						     jobject, jobject,
						     jfloat);
 */

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setLongNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;J)V
  JNIEXPORT static void JNICALL Java_java_io_VMObjectStreamClass_setLongNative
    (JNIEnv *, jclass, jobject, jobject, jlong);
 */

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setIntNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;I)V
  JNIEXPORT static void JNICALL Java_java_io_VMObjectStreamClass_setIntNative
    (JNIEnv *, jclass, jobject, jobject, jint);
 */

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setShortNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;S)V
  JNIEXPORT static void JNICALL
    Java_java_io_VMObjectStreamClass_setShortNative (JNIEnv *, jclass,
						     jobject, jobject,
						     jshort);
 */

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setCharNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;C)V
  JNIEXPORT static void JNICALL Java_java_io_VMObjectStreamClass_setCharNative
    (JNIEnv *, jclass, jobject, jobject, jchar);
 */

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setByteNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;B)V
  JNIEXPORT static void JNICALL Java_java_io_VMObjectStreamClass_setByteNative
    (JNIEnv *, jclass, jobject, jobject, jbyte);
 */

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setBooleanNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;Z)V
  JNIEXPORT static void JNICALL
    Java_java_io_VMObjectStreamClass_setBooleanNative (JNIEnv *, jclass,
						       jobject, jobject,
						       jboolean);
 */

/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    setObjectNative
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;Ljava/lang/Object;)V
  JNIEXPORT static void JNICALL
    Java_java_io_VMObjectStreamClass_setObjectNative (JNIEnv *, jclass,
						      jobject, jobject,
						      jobject);
 */

#ifdef __cplusplus
}
#endif
#endif
