/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_reflect_Field */

#ifndef _Included_java_lang_reflect_Field
#define _Included_java_lang_reflect_Field
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetDeclaringClass
 * Signature: ([B)Ljava/lang/Class;
 */
  JNIEXPORT static jclass JNICALL
    Java_java_lang_reflect_Field_nativeGetDeclaringClass (JNIEnv *, jclass,
							  jbyteArray);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetName
 * Signature: ([B)Ljava/lang/String;
 */
  JNIEXPORT static jstring JNICALL Java_java_lang_reflect_Field_nativeGetName
    (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetModifiers
 * Signature: ([B)I
 */
  JNIEXPORT static jint JNICALL
    Java_java_lang_reflect_Field_nativeGetModifiers (JNIEnv *, jobject,
						     jbyteArray);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetType
 * Signature: ([B)Ljava/lang/Class;
 */
  JNIEXPORT static jclass JNICALL Java_java_lang_reflect_Field_nativeGetType
    (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetReference
 * Signature: ([BLjava/lang/Object;)Ljava/lang/Object;
 */
  JNIEXPORT static jobject JNICALL
    Java_java_lang_reflect_Field_nativeGetReference (JNIEnv *, jobject,
						     jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetBoolean
 * Signature: ([BLjava/lang/Object;)Z
 */
  JNIEXPORT static jboolean JNICALL
    Java_java_lang_reflect_Field_nativeGetBoolean (JNIEnv *, jobject,
						   jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetByte
 * Signature: ([BLjava/lang/Object;)B
 */
  JNIEXPORT static jbyte JNICALL Java_java_lang_reflect_Field_nativeGetByte
    (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetChar
 * Signature: ([BLjava/lang/Object;)C
 */
  JNIEXPORT static jchar JNICALL Java_java_lang_reflect_Field_nativeGetChar
    (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetShort
 * Signature: ([BLjava/lang/Object;)S
 */
  JNIEXPORT static jshort JNICALL Java_java_lang_reflect_Field_nativeGetShort
    (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetInt
 * Signature: ([BLjava/lang/Object;)I
 */
  JNIEXPORT static jint JNICALL Java_java_lang_reflect_Field_nativeGetInt
    (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetLong
 * Signature: ([BLjava/lang/Object;)J
 */
  JNIEXPORT static jlong JNICALL Java_java_lang_reflect_Field_nativeGetLong
    (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetFloat
 * Signature: ([BLjava/lang/Object;)F
 */
  JNIEXPORT static jfloat JNICALL Java_java_lang_reflect_Field_nativeGetFloat
    (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeGetDouble
 * Signature: ([BLjava/lang/Object;)D
 */
  JNIEXPORT static jdouble JNICALL
    Java_java_lang_reflect_Field_nativeGetDouble (JNIEnv *, jobject,
						  jbyteArray, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetReference
 * Signature: ([BLjava/lang/Object;Ljava/lang/Object;)V
 */
  JNIEXPORT static void JNICALL
    Java_java_lang_reflect_Field_nativeSetReference (JNIEnv *, jobject,
						     jbyteArray, jobject,
						     jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetBoolean
 * Signature: ([BLjava/lang/Object;Z)V
 */
  JNIEXPORT static void JNICALL Java_java_lang_reflect_Field_nativeSetBoolean
    (JNIEnv *, jobject, jbyteArray, jobject, jboolean);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetByte
 * Signature: ([BLjava/lang/Object;B)V
 */
  JNIEXPORT static void JNICALL Java_java_lang_reflect_Field_nativeSetByte
    (JNIEnv *, jobject, jbyteArray, jobject, jbyte);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetChar
 * Signature: ([BLjava/lang/Object;C)V
 */
  JNIEXPORT static void JNICALL Java_java_lang_reflect_Field_nativeSetChar
    (JNIEnv *, jobject, jbyteArray, jobject, jchar);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetShort
 * Signature: ([BLjava/lang/Object;S)V
 */
  JNIEXPORT static void JNICALL Java_java_lang_reflect_Field_nativeSetShort
    (JNIEnv *, jobject, jbyteArray, jobject, jshort);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetInt
 * Signature: ([BLjava/lang/Object;I)V
 */
  JNIEXPORT static void JNICALL Java_java_lang_reflect_Field_nativeSetInt
    (JNIEnv *, jobject, jbyteArray, jobject, jint);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetLong
 * Signature: ([BLjava/lang/Object;J)V
 */
  JNIEXPORT static void JNICALL Java_java_lang_reflect_Field_nativeSetLong
    (JNIEnv *, jobject, jbyteArray, jobject, jlong);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetFloat
 * Signature: ([BLjava/lang/Object;F)V
 */
  JNIEXPORT static void JNICALL Java_java_lang_reflect_Field_nativeSetFloat
    (JNIEnv *, jobject, jbyteArray, jobject, jfloat);

/*
 * Class:     java_lang_reflect_Field
 * Method:    nativeSetDouble
 * Signature: ([BLjava/lang/Object;D)V
 */
  JNIEXPORT static void JNICALL Java_java_lang_reflect_Field_nativeSetDouble
    (JNIEnv *, jobject, jbyteArray, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
